### ISSUE TITLE
batchDF does not support  the field "quote"

### ISSUE THREAD

**Issue by TheRealNBA** [timkpaine/pyEX#100]
Hi,

when i call 

myDb.iex.batchDF(["AAPL", "MSFT"], ["quote"])

I get the error

KeyError: 'quote'

myDb.iex.batch(["AAPL", "MSFT"], ["quote"])
or
myDb.iex.batchDF(["AAPL", "MSFT"], ["chart"])
myDb.iex.batchDF(["AAPL", "MSFT"], ["news"])

on the other hand works fine

Thx for the help

**Comment by timkpaine** [comment]
thanks for the report, I've added a workaround

**Comment by TheRealNBA** [comment]
Hi,
for some reason the function returns a dictionary now instead of a pandas Data Frame.

e.g.
quotes = myDb.iex.batchDF(segSymbList[i], ["quote"])
return quotes 

gives me
 {'quote':    avgTotalVolume calculationPrice  change  changePercent close closeTime  \
 0         5289707             tops  -1.591       -0.09427  None      None   
 0         2843357             tops  -6.040       -0.09533  None      None   
 0         7610201             tops  -2.791       -0.25835  None      None   
 0         9559761             tops   1.240        0.04033  None      None  

I also can't access quotes["avgTotalVolume"]  as it raises a key error ...

**Comment by timkpaine** [comment]
it returns a dict `{KEY: data frame}`
