### ISSUE TITLE
Old IEX API is deprecated. For a free API token, sign up at https://iexcloud.io

### ISSUE THREAD

**Issue by lbottan** [timkpaine/pyEX#105]
Just installed 0.2.1....

put iexcloud in sandbox and got the public key...
these 3 lines of code:

import pyEX as p
p.Client(api_token="Tpk_xxxxxxxxxxxxxx", version='sandbox')
p.internationalSymbolsDF().head()

I get:

******************************************* 

PyEXception                               Traceback (most recent call last)
<ipython-input-8-f342cdf29f6c> in <module>
      4 p.Client(api_token="Tpk_xxxxx", version='sandbox')
      5 
----> 6 p.internationalSymbolsDF().head()

~\AppData\Roaming\Python\Python37\site-packages\pyex-0.2.1-py3.7.egg\pyEX\refdata\symbols.py in internationalSymbolsDF(region, exchange, token, version, filter)
    233         DataFrame: result
    234     '''
--> 235     df = pd.DataFrame(internationalSymbols(region, exchange, token, version, filter))
    236     _toDatetime(df)
    237     _reindex(df, 'symbol')

c:\users\lbottan\appdata\local\continuum\anaconda3\lib\site-packages\temporal_cache-0.1.1-py3.7.egg\temporalcache\expire.py in _wrapped_foo(*args, **kwargs)
     77             kwargs = {k: frozendict(v) if isinstance(v, dict) else tuple(v) if isinstance(v, list) else v for k, v in kwargs.items()}
     78 
---> 79             return foo(*args, **kwargs)
     80         return _wrapped_foo
     81     return _wrapper

c:\users\xxx\appdata\local\continuum\anaconda3\lib\site-packages\temporal_cache-0.1.1-py3.7.egg\temporalcache\persistent_lru_cache.py in wrapper(*args, **kwds)
    202                         hits += 1
    203                         return result
--> 204                 result = user_function(*args, **kwds)
    205                 with lock:
    206                     if key in cache:

~\AppData\Roaming\Python\Python37\site-packages\pyex-0.2.1-py3.7.egg\pyEX\refdata\symbols.py in internationalSymbols(region, exchange, token, version, filter)
     98     elif exchange:
     99         return _getJson('ref-data/exchange/{exchange}/symbols'.format(exchange=exchange), token, version, filter)
--> 100     return _getJson('ref-data/region/us/symbols', token, version, filter)
    101 
    102 

~\AppData\Roaming\Python\Python37\site-packages\pyex-0.2.1-py3.7.egg\pyEX\common.py in _getJson(url, token, version, filter)
    132             return _getJsonIEXCloudSandbox(url, token, version, filter)
    133         return _getJsonIEXCloud(url, token, version, filter)
--> 134     return _getJsonOrig(url)
    135 
    136 

~\AppData\Roaming\Python\Python37\site-packages\pyex-0.2.1-py3.7.egg\pyEX\common.py in _getJsonOrig(url)
    136 
    137 def _getJsonOrig(url):
--> 138     raise PyEXception('Old IEX API is deprecated. For a free API token, sign up at https://iexcloud.io')
    139 
    140 

PyEXception: Old IEX API is deprecated. For a free API token, sign up at https://iexcloud.io

WHY?

**Comment by timkpaine** [comment]
You create a client but don't use the return value, then you call international symbols without a token or version? I think you meant to store the client in `c` and call `c.infernationalSymbols` instead of calling the raw function.

**Comment by lbottan** [comment]
you are right (of course)! 
my bad!

one last question, you are very kind, I am trying to get all symbols from london stock exchange and than export daily data... but i can't understand how to do it...

p.internationalSymbolsDF(token=token, version=version).to_csv("exp.txt")

I get a file where apparently there are only US symbols ...

Sorry for my questions, I am a newbie.

also:

-adjusted close is available?
-can i get more than 5yrs historical data?
-if i want to normlize to 1 currency is there any simplified way?

Thanks in advance for your support.

**Comment by timkpaine** [comment]
These are all questions for the underlying API, not this wrapper library.

https://iexcloud.io/docs/api/
https://iexcloud.io/docs/api/#support
