### ISSUE TITLE
possible problem on historicalFXDF

### ISSUE THREAD

**Issue by lbottan** [timkpaine/pyEX#106]
I have two issue with:

py.historicalFXDF(symbols="EURCHF")

i get this strage dataframe as result

![image](https://user-images.githubusercontent.com/63106707/78649816-467df280-78be-11ea-9399-b78e50ab83e7.png)

Also i can't understand how to get 5yrs history of this cross, o get only last.

**Comment by timkpaine** [comment]
Yep it's a big, the Json needs to be parsed out differently.

**Comment by lbottan** [comment]
also when i use historicalFX shouldn't i get the full history? i instead i get 1 value only.

**Comment by lbottan** [comment]
Dear Tim,
I apologize for disturbing, just for my planning, do you have any plan for
fixing this bug and the other one connected I posted?


Il Mar 7 Apr 2020, 14:43 Tim Paine <notifications@github.com> ha scritto:

**Comment by timkpaine** [comment]
this implemented the timeseries api, so you have to specify `from_`, `to_`, `on`, `first`, `last`. Implemented and fixed in #114 
![Screen Shot 2020-08-04 at 15 11 47](https://user-images.githubusercontent.com/3105306/89334907-453eb580-d665-11ea-9deb-79da6e315448.png)
