### ISSUE TITLE
possible bug on fxSymbolsDF()

### ISSUE THREAD

**Issue by lbottan** [timkpaine/pyEX#107]
If i use py.fxSymbolsDF() i get this output (type:list):

![image](https://user-images.githubusercontent.com/63106707/78687837-e0609200-78f4-11ea-9d1e-51038d3460fc.png)

I am not 100% sure is the expected output.
If I convert it to Dataframe I get

![image](https://user-images.githubusercontent.com/63106707/78688109-31708600-78f5-11ea-9f7d-81e1dabd87a7.png)

**Comment by timkpaine** [comment]
@lbottan this is expected, it returns a list with 2 data frames. The first is symbols, the second is pairs
