### ISSUE TITLE
A 'symbol not found' response to a batchDF raises expection

### ISSUE THREAD

**Issue by xtracool** [timkpaine/pyEX#108]
Hi,

Daily I'm downloading the list of stocks from NASDAQ and using IEX to get the latest stock prices.  It seems that the NASDAQ file has ticker symbols that are not valid on the IEX platform.  For example BRKA, but BRK.A is OK.  I batch about 40 symbols per quote call.

During a batchDF call, if there is a symbol that isn't on the exchange, an exception is raised and the entire operation is aborted vs just skipping over the symbols that are not found.

Is there a way around this? 

Thanks!
-Ven

**Comment by timkpaine** [comment]
https://github.com/iexg/IEX-API/issues/1537
