### ISSUE TITLE
FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

### ISSUE THREAD

**Issue by ckrysinski** [timkpaine/pyEX#111]
Getting this 'FutureWarning' for a number of DataFrame calls:

**In Jupyter:** 
anaconda3\lib\site-packages\pyEX\stocks\marketInfo.py:183: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = pd.io.json.json_normalize(val, 'rawData')

**pyEX calls tried:**
c.ipoUpcomingDF('aapl')
c.analystRecommendationsDF('aapl')

There's likely more.  Just wanted to give a heads up on this.

**Comment by timkpaine** [comment]
the lower bound on pandas is < 1.0, these occur only in new pandas versions
https://github.com/timkpaine/pyEX/blob/master/setup.py#L28
