### ISSUE TITLE
Docs Posted on ReadTheDocs Missing ToC Links

### ISSUE THREAD

**Issue by ra-lukas** [timkpaine/pyEX#121]
Somewhat of a small matter: The docs posted on readthedocs.io are only showing the "Client" under API Documentation.  

Please see attached image.  Inside is an example of how to navigate the site with the full array of links.
![Untitled](https://user-images.githubusercontent.com/64919532/92305426-43625d80-ef55-11ea-9c74-dc9e40a34e3d.png)

**Comment by timkpaine** [comment]
I recently got rid of the independent docs in favor of just the client, since the client has everything anyway it makes it easier to autodoc. The docs are clear that the functions can be used independently so really it's just the screenshot that's wrong

**Comment by ra-lukas** [comment]
Understood.  Thanks Tim.
