### ISSUE TITLE
Is there a method to get messagebudget? 

### ISSUE THREAD

**Issue by illi4** [timkpaine/pyEX#123]
I would like to use this lib and to get information on the [messages budget](https://iexcloud.io/docs/api/#message-budget) for my account. I can't find the right one (there is no account in the endpoints). Could it be added if not available? Thanks

**Comment by timkpaine** [comment]
That api is to modify the message budget. [Metadata](https://iexcloud.io/docs/api/#metadata) would be used to get it. I will add an explicit `client.metadata()` function but you can already access with `client.account()`. Keep in mind you need too use your secret key.

**Comment by illi4** [comment]
@timkpaine could you please advise how to provide secret key when calling this method? I can't find a way through code

**Comment by illi4** [comment]
Oh NM
