### ISSUE TITLE
AttributeError: module 'pyEX' has no attribute 'topsWS'

### ISSUE THREAD

**Issue by smjure** [timkpaine/pyEX#128]
Seems that the method topsWS was removed/relocated, hence example ws.ipynb doesn't work anymore. Could that be fixed, thank you.

![image](https://user-images.githubusercontent.com/22912191/96855223-b750ba80-145c-11eb-83f9-88e89eb26555.png)

**Comment by timkpaine** [comment]
You should switch to the SSE endpoint 
https://github.com/timkpaine/pyEX/blob/main/pyEX/marketdata/sse.py#L36
https://iexcloud.io/docs/api/#sse-streaming

WS support was removed in this PR https://github.com/timkpaine/pyEX/pull/66/files?file-filters%5B%5D=.py and was gone as of 0.1.14
