### ISSUE TITLE
Threading with pyEx

### ISSUE THREAD

**Issue by smjure** [timkpaine/pyEX#129]
Have checked the library, it's pretty extensive and awesome, thank you for the great work. What would be an efficient way to incorporate threading or asyncio for real-time streaming? Would be great to have an example on it or to add it as a feature/method. Am missing this in comparison to Alpaca or polygon.io, it's very efficient and needed.

**Comment by timkpaine** [comment]
Take a look at https://github.com/timkpaine/pyEX/pull/131 i've added better support for asyncio integration for SSE endpoints
