### ISSUE TITLE
Avoid pandas for efficiency

### ISSUE THREAD

**Issue by petric3** [timkpaine/pyEX#132]
Thanks for the library, comprehensive work done 👍 I went through the code and I would strongly recommend avoiding `pandas`. As an intraday algo trader I consider IEX data streaming of the highest value. Out there are many data feeds that provide bars and news data free of charge or included in brokerage plans, therefore IEX (added) value is exclusively in data streaming. Hence, speed is crucial!! Pandas contain a great deal of overhead, so I'd leave data in dictionary format and/or similar. Please consider this example:

 ```
import pandas as pd
 from ttictoc import tic,toc
 reps  = 10000 # "messages" 

 prices = np.random.normal(100,20,(1,5)) # some random price, say Open,High,Low,Close,Volume
 
 # ------------ pandas usage
 stock = pd.DataFrame() # init
 tic()
 for _ in range(reps): # loop simulating data streaming
     stock = pd.concat((stock,pd.DataFrame(prices)))
 print(F'pandas     time: {toc():.3f}s')
 #print(stock[:10]) # uncomment to check the results
 
 # ----------- dictionary usage
 stock = {'Open':[],'High':[],'Low':[],'Close':[],'Volume':[]} # init
 tic()
 for _ in range(reps): # loop simulating data streaming
     stock['Open'].append(   prices[0,0])
     stock['High'].append(   prices[0,1])
     stock['Low'].append(    prices[0,2])
     stock['Close'].append(  prices[0,3])
     stock['Volume'].append( prices[0,4])
 print(F'dictionary time: {toc():.3f}s')
 
 stock = pd.DataFrame(stock) # !! Seamless dict conversion into pandas
 #print(stock[:10]) # uncomment to check the results
```

The speed difference is huge, in my case >500x! Note that only 10k "messages" are used. I played in sandbox and on a daily basis I'd use around 20M messages for trading. If I develop a scanner based on IEX data, then several times more messages would be needed. This is an example just of managing "storage" of streamed data in pandas, calculation would add up further overhead.  

On the other hand, seamless conversion of the dict into pd.DataFrame() can be done in a single line for whoever wants to calc in pandas (see at the end of the code). 

Since pandas dataframes are basically dictionaries, removing_pandas/upgrading of the library would not require a great deal of work. Just a bit of reflection from an intraday algo trader. Keep up with the great work  👍

**Comment by timkpaine** [comment]
Did you look at the code?

**Comment by petric3** [comment]
I have, for example:
![image](https://user-images.githubusercontent.com/23335373/97579048-e2ee1a80-19f1-11eb-9ea6-3c35f45036e5.png)

**Comment by timkpaine** [comment]
So if you don't want the pandas wrapper, wouldn't `cryptoBook` do what you want?
