### ISSUE TITLE
[deepSSE] HTTPError: 404 Client Error: Not Found for url: https://cloud-sse.iexapis.com

### ISSUE THREAD

**Issue by smjure** [timkpaine/pyEX#139]
Im playing with paid account. When trying 
`c = iex.marketdata.sse.deepSSE(symbols='TSLA,AAPL',on_data=on_data_func,token='pk_*****')` the following error raises:
![image](https://user-images.githubusercontent.com/22912191/97807338-7b89d200-1c60-11eb-810a-6cd9eb4290f2.png)

Similarly, if trying: 
```
 c = iex.Client()  # token is under env var: IEX_TOKEN
 c.deepSSE(symbols='AAPL,TSLA')# , on_data=on_data_func)
```
different error, i.e. error 500 is raised, but then again pointing to URL problem:
![image](https://user-images.githubusercontent.com/22912191/97807236-04ecd480-1c60-11eb-853f-5bf7ee17878c.png)

How to overcome the problem? Thank you...

I may mention, that `c.topsSSE` works fine:
![image](https://user-images.githubusercontent.com/22912191/97807260-1fbf4900-1c60-11eb-9514-ab9d00318cda.png)

[... but e.g. c.topsSSEAsync() client has no attribute topsSSEAsync, which would be expected to have (I can open new issue for this one if preferred)
![image](https://user-images.githubusercontent.com/22912191/97807284-39609080-1c60-11eb-8849-75e0ad1ae610.png)
]

**Comment by timkpaine** [comment]
The deep endpoint requires channels to be specified, looks like this is missing from the doctoring so I will add it. 

Also looks like those SSE methods are missing from the client, I will add them as well.
