### ISSUE TITLE
tradesSSE and bookSSE concurrently

### ISSUE THREAD

**Issue by smjure** [timkpaine/pyEX#144]
DEEP or deepSSE allows only one symbol to stream at once. Is there some elegant way to run tradesSSE and bookSSE concurrently? Thank you.

PS: latest version throws the following error
![image](https://user-images.githubusercontent.com/22912191/98032638-92712580-1e14-11eb-8ddc-1cf0dabebddc.png)

**Comment by timkpaine** [comment]
Best bet is to merge the async generator variants of these methods. https://stackoverflow.com/questions/48830795/merging-async-iterables-in-python3

**Comment by timkpaine** [comment]
other bug fixed in v0.2.8
