### ISSUE TITLE
Collapsing the output in all.ipynb?

### ISSUE THREAD

**Issue by tardebut** [timkpaine/pyEX#145]
Hi Tim,

Thanks for pyEX. New to the field, I started with this application. 

From a fire tablet, it takes too long to view the code of the example all.ipynb. Not just in this repository but in a fully managed notebook at AWS as well. It nearly freezes. Collapsing all outputs solve the situation and could make it available to others in this same situation.

Thanks again,

Omar

**Comment by timkpaine** [comment]
I can't repro on a 2013 MacBook Pro. Hiding the outputs would somewhat defeat the purpose of being able to view the outputs without installing, if you just want to know what methods are available you can look at the README. If you want to get a sample of what the data looks like, the API docs have sample outputs for everything:https://iexcloud.io/docs/api/
