### ISSUE TITLE
Unrecognized batch request field: intraday-prices

### ISSUE THREAD

**Issue by juanifioren** [timkpaine/pyEX#187]
This was working until last version. Am I missing something?

![Screenshot from 2020-12-30 15-07-24](https://user-images.githubusercontent.com/5168681/103372433-cd0fdb00-4ab0-11eb-80e8-6d0055a4cad6.png)

**Comment by timkpaine** [comment]
now enforced that it has to be in [this list](https://github.com/timkpaine/pyEX/blob/main/pyEX/common.py#L115)

**Comment by juanifioren** [comment]
@timkpaine Ok makes sense, I changed to `iex_client.batch(fields=['chart'], symbols=['TSLA'], range_='1d')` and seems to be fine to show (daily chart or last trading day).

This is confusing since `intraday-prices` is inside the stock section :thinking: 
![Screenshot from 2020-12-30 15-29-16](https://user-images.githubusercontent.com/5168681/103373473-d189c300-4ab3-11eb-9ff7-527718508e95.png)

**Comment by timkpaine** [comment]
it is supported, just needs to be added to that list
