### ISSUE TITLE
Add support for Cloud Cache on IEX

### ISSUE THREAD

**Issue by ilyanoskov** [timkpaine/pyEX#197]
**Describe the solution you'd like**
I would like to be able to use cache=true parameter on each function call. This way it would be possible to utilize this feature: https://iexcloud.io/cloud-cache/

**Describe alternatives you've considered**
I do not understand how the current caching implementation works in this library. My scripts run in intervals so the data cannot be persisted in memory. I considered implementing my own caching layer but it would be too much work. It seems that IEX has a very good solution with Cloud Cache.

**Comment by timkpaine** [comment]
Cloud cache is now free for individual and business plans and automatically enabled https://iexcloud.io/cloud-cache/
