### ISSUE TITLE
Client.usage() does not work using sandbox tokens.

### ISSUE THREAD

**Issue by dogon11** [timkpaine/pyEX#199]
**Description** 
When trying to use sandbox API tokens, the method Client.usage() raises pyEX.common.pyEXception: "Requires secret token!" The cause follows line 875 in pyEX/common.py, under the function _requireSecret(). The check for secret tokens checks for "sk" token prefixes, but sandbox tokens add an additional "T", so a sandbox secret API token starts with the prefix "Tsk". 

**To Reproduce**
Run the following code in a .py file:

import pyEX as p
SECRET_TOKEN = # Insert your secret sandbox token here, starting with "Tsk".
usage_return = p.usage(type="messages", token=SECRET_TOKEN, version='sandbox')

**Expected behavior**
I expected I would be able to use sandbox API tokens to test functionality of my code before spending messages on using production data.

**Comment by timkpaine** [comment]
fixed in #200
