### ISSUE TITLE
intraday chart request not working

### ISSUE THREAD

**Issue by PhilipNgPack** [timkpaine/pyEX#210]
hello, thank you so much for your library!

Intraday stock information functionality doesn't seem to be working.

```df = self.c.chartDF(symbol="AAPL", timeframe="1d", date="2018-11-28")```

results in the error:

```pyEX.common.PyEXception: ('Response 400 - ', 'You have supplied invalid values for this request')```

Did the IEX api get updated or something?

**Comment by timkpaine** [comment]
https://iexcloud.io/docs/api/#historical-prices

**Comment by PhilipNgPack** [comment]
> Please RTD about data availability https://iexcloud.io/docs/api/#historical-prices

Thanks for the reply, I understand that intraday is given for the last 30 days, my example was copied from a previous issue and I forgot to update the date.

Regardless, am I missing something with the signature of the method call? I tried different combinations of parameters and the endpoint still doesn't like the arguments passed from the library

```df = self.c.chartDF(symbol='AAPL',timeframe='1d', date='2021-01-11')```

**Comment by PhilipNgPack** [comment]
Nevermind, the date formatting was incorrect. The API wants it in the form: YYYYMMDD
