### ISSUE TITLE
Data type issue with talib

### ISSUE THREAD

**Issue by EsiNaderi** [timkpaine/pyEX#211]
Some functions throw error because talib doesn't like the type of data that is passed to it . This issue seems to be related to this:

https://stackoverflow.com/questions/22993124/ta-lib-numpy-assertionerror-real-is-not-double/25191773

For example, p.client.Client.mfi returns this error:

`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-48-2974305e9030> in <module>
----> 1 obv_results = p.client.Client.mfi(c,'AAPL')
      2 obv_results

~/anaconda3/envs/pyex/lib/python3.8/site-packages/pyEX/studies/technicals/momentum.py in mfi(client, symbol, timeframe, highcol, lowcol, closecol, volumecol, period)
    395     """
    396     df = client.chartDF(symbol, timeframe)
--> 397     x = t.MFI(
    398         df[highcol].values,
    399         df[lowcol].values,

~/anaconda3/envs/pyex/lib/python3.8/site-packages/talib/__init__.py in wrapper(*args, **kwargs)
     25 
     26             if index is None:
---> 27                 return func(*args, **kwargs)
     28 
     29             # Use Series' float64 values if pandas, else use values as passed

talib/_func.pxi in talib._ta_lib.MFI()

talib/_func.pxi in talib._ta_lib.check_array()

Exception: input array type is not double`

Almost the same thing happens for some other methods such as obv and stochrsi. Methods such as wma, sma, etc work fine. 

How I can fix it without going inside source and add data conversion to each line  that passes data to talib?

**Comment by timkpaine** [comment]
@EsiNaderi you're likely the first one to use these, I will make sure everything is casted to float in #209

**Comment by EsiNaderi** [comment]
Thanks this solves it. However, the issue still persists for "stochrsi".
