### ISSUE TITLE
Ending a SSE subscription

### ISSUE THREAD

**Issue by dtasgaon** [timkpaine/pyEX#220]
Sorry, I couldn't figure this out, and thought I'll open an issue here. Apologies if this is covered in docs; would greatly appreciate a pointer there if so.

Once a SSE stream is subscribed to, how does one go about ending the subscription?

```
import time
from threading import Thread
import pyEX

client = pyEX.Client()

def print_message(data):
    print(data)

thread = Thread(
    target=client.stocksUS1MinuteSSE,
    kwargs={"on_data": print_message}
)
thread.start()

# simulate the day passing by
time.sleep(30)

# how do I end the subscription after 30 seconds?
```

The pattern at [this line]( https://github.com/timkpaine/pyEX/blob/01e208e93ea3c9d85ec25bfbac6c30be57c27967/pyEX/common.py#L847) suggests that we need to raise a `PyEXStopSSE`  exception inside the `on_data` event handler to stop listening.

However, that can only work when an event is raised. Is there a way to stop listening outside the event handler? I could set a `threading.Event` to signal the end, but where in the thread should I check for the event?

**Comment by dtasgaon** [comment]
Here's the best version I have so far. Would love guidance on whether this is a good pattern. 

After the stop request is made, the listening stops after the next event is received from the server.

```
import time
from threading import Thread, Event
import pyEX

client = pyEX.Client()
stop_listening = Event()

def print_message(data):
    print(data)
    if stop_listening.is_set():
        raise pyEX.PyEXStopSSE

thread = Thread(
    target=client.stocksUS1MinuteSSE,
    kwargs={"on_data": print_message}
)
thread.start()

# simulate the day passing by
time.sleep(30)

# set an Event, which will cause the listening to stop
#   at the next event received from the server
stop_listening.set()
thread.join()

```

**Comment by timkpaine** [comment]
@dtasgaon this is the best you can do in the non-async version. I will make the async versions immediately cancelleable in a PR

**Comment by dtasgaon** [comment]
@timkpaine I'll leave the issue open for now. I'll defer to you on when to close the issue -- now or when the PR is created.

Thank you for a wonderful library. Great work!!

**Comment by timkpaine** [comment]
ok #224 presents 2 new ways of stopping:

With Asyncio:

```python
import asyncio
import pyEX as p

# instantiate client
c = p.Client(version="sandbox")

# instantiate end event
end = asyncio.Event()

# exit coroutine, set `end` when you want to stop
async def exit():
    await asyncio.sleep(2)
    end.set()

# main loop
async def run():
    # run exit, will end in 2s
    asyncio.ensure_future(exit())

    # iterate through newsSSEAsync
    async for message in c.newsSSEAsync("AAPL,", end):
        print(message)

# get event loop
loop = asyncio.get_event_loop()

# run until complete (in 2s when `end.set()`)
loop.run_until_complete(run())
```

Non-async:

```python
import sys
import threading
import time

exit = threading.Event()

exitthread = c.newsSSE("AAPL", on_data=print, exit=exit)

time.sleep(2)
exit.set()
```
