### ISSUE TITLE
Support for "NoUTP" on SSE

### ISSUE THREAD

**Issue by dtasgaon** [timkpaine/pyEX#223]
I could not find a way to handle this yet, so would love to confirm my understanding before turning this into a feature request.

Is there a way to adjust SSE calls to use the "NoUTP" versions? Please see this example from [IEX docs](https://iexcloud.io/docs/api/#sse-streaming). Note the `NoUTP` in the endpoint.

```
curl --header 'Accept: text/event-stream' https://cloud-sse.iexapis.com/stable/stocksUSNoUTP?symbols=spy&token=YOUR_TOKEN
```

As an example, the [`stocksUS1SecondSSE()`](https://github.com/timkpaine/pyEX/blob/01e208e93ea3c9d85ec25bfbac6c30be57c27967/pyEX/marketdata/stock.py#L76-L77) function uses `"stocksUS1Second"`, and doesn't seem to provide a way to use the `NoUTP` endpoint. Is there a way to do that?

**Comment by timkpaine** [comment]
![image](https://user-images.githubusercontent.com/3105306/108644647-e19f9c80-747d-11eb-9e08-cc1333cee5b1.png)

**Comment by dtasgaon** [comment]
Thanks @timkpaine. A different example may have better explained what I see. 

This: 

```
https://cloud-sse.iexapis.com/stable/stocksUSNoUTP1Second
```

is a `NoUTP` variation of the `1Second` endpoint. These `NoUTP` variations are not explicitly listed on IEX Docs, but they do exist.

There doesn't seem to be a way to trigger this endpoint through the `Client` API.  I'll leave it to your judgment on whether to add this to the API.

I had to resort to using the underlying `SSEClient` to connect to that endpoint.

**Comment by timkpaine** [comment]
we will add these to the docs, and I will add them here
