### ISSUE TITLE
DataFrame header alignment

### ISSUE THREAD

**Issue by rseningen** [timkpaine/pyEX#27]
Nice work with pyEX!  
Are the dataframe headers supposed to be offset?  The date headers are in the second row which is empty otherwise.  This can be seen in the examples:  https://github.com/timkpaine/pyEX/blob/master/all.ipynb

![image](https://user-images.githubusercontent.com/1854354/46099794-c5f11880-c195-11e8-94d3-4113771d9b72.png)

**Comment by timkpaine** [comment]
@rseningen the dataframe has a multi index, first by day and then by minute

**Comment by timkpaine** [comment]
this is the default html rendering for pandas multi indexed data frames

**Comment by timkpaine** [comment]
if you're looking for a better view I can recommend perspective
![screen shot 2018-09-26 at 3 05 53 pm](https://user-images.githubusercontent.com/3105306/46103028-c2618f80-c19d-11e8-941d-1687e0c0f42c.png)

**Comment by rseningen** [comment]
Thanks!
