### ISSUE TITLE
not possible to exit SSE in a non-async mode

### ISSUE THREAD

**Issue by rbtbar** [timkpaine/pyEX#278]
The SSEClient invokes [self._connect()](https://github.com/btubbs/sseclient/blame/master/sseclient.py#L100) while handling the  [requests.RequestException](https://github.com/btubbs/sseclient/blame/master/sseclient.py#L97) error, so that it is not possible to stop streaming.

```python
def on_data(d):
    print(f'{datetime.now()} on_data {len(d)=}')

event = Event()
iex_api.streaming.stocksUSNoUTP1SecondSSE(symbols=tickers, on_data=on_data, exit=event)
time.sleep(1)
event.set()
print('Event set')
time.sleep(100)
```

```
2021-05-27 **20:43:39**.421475 on_data len(d)=1
Event set
2021-05-27 **20:43:44**.156520 on_data len(d)=1
```

**Expected behavior**
after event.set() the underlying connection should be closed forever

**Comment by timkpaine** [comment]
This is a known issue:
https://github.com/psf/requests/issues/5372

I will see if I can work around it
