### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by mcgwebdesign** [timkpaine/pyEX#29]
```
  Failed building wheel for ujson
Command "c:\programdata\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\xxx\\appdata\\local\\temp\\pip-install-59od11\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\xxx\appdata\local\temp\pip-record-oignye\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-install-59od11\ujson\
```

any workaround for this?

**Comment by timkpaine** [comment]
can you pip install jason manually?

**Comment by mcgwebdesign** [comment]
Looks like no, tried on two different computers python 2 and 3 same result.

**Comment by timkpaine** [comment]
ive done another release removing the ujson dependency

**Comment by mcgwebdesign** [comment]
confirmed. thanks

**Comment by mcgwebdesign** [comment]
is ujson a dependency again? Can't seem to install it

**Comment by timkpaine** [comment]
No, what is the error:
https://github.com/timkpaine/pyEX/blob/6008e7d12c3dd40415548d3ce3dc8b23ffef5d72/pyEX/common.py#L4

**Comment by mcgwebdesign** [comment]
` Failed building wheel for ujson
Command "c:\programdata\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\xx\\appdata\\local\\temp\\pip-install-b0a9vh\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\xx\appdata\local\temp\pip-record-u5wpvd\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\xx\appdata\local\temp\pip-install-b0a9vh\ujson\`

**Comment by timkpaine** [comment]
can you try `--no-cache-dir` for pip
