### ISSUE TITLE
WS example

### ISSUE THREAD

**Issue by mcgwebdesign** [timkpaine/pyEX#30]
hello,

Can you include a working WS example in the notebook? I'm not able to get the on_data callback to work as expected on updates to the TOPS feed. 

```
pyEX.topsWS(symbols='SIRI', on_data=print)
<pyEX.common.WSClient at 0x97eb940>
```

Checking the DF method shows updates coming through.

**Comment by timkpaine** [comment]
notice the return value, it is a blocking WS client which you can call `run` on:
![screen shot 2018-10-08 at 12 40 05 pm](https://user-images.githubusercontent.com/3105306/46622077-4f3e0e80-caf7-11e8-9991-c0ae34a4d754.png)
