### ISSUE TITLE
bulkBatchDF returns keyerror

### ISSUE THREAD

**Issue by maartenmennes** [timkpaine/pyEX#32]
When running bulkBatchDF I get the following error:

![image](https://user-images.githubusercontent.com/1139180/47181286-e9395e80-d322-11e8-8ef0-3ab7df7974e8.png)

**Comment by timkpaine** [comment]
How old is your pandas?

**Comment by timkpaine** [comment]
too old : https://pandas.pydata.org/pandas-docs/version/0.23.4/whatsnew.html#concatenation-will-no-longer-sort

**Comment by maartenmennes** [comment]
confirmed, working fine in 0.23.4
perhaps add > 0.23.0 to requirements?

**Comment by timkpaine** [comment]
I don't like to add strict version requirements usually, most of the code will work without new pandas
