### ISSUE TITLE
p.chartDF() doesn't return unadjusted prices

### ISSUE THREAD

**Issue by DJones1309** [timkpaine/pyEX#350]
<img width="1728" alt="Screen Shot 2021-12-28 at 3 39 33 PM" src="https://user-images.githubusercontent.com/83872820/147605557-fe4684bb-8c33-4176-9e67-f3a18b9cb5f0.png"><img width="821" alt="Screen Shot 2021-12-28 at 3 40 00 PM" src="https://user-images.githubusercontent.com/83872820/147605649-52ccc0dc-11a9-48b3-9fcf-e71f0df5f16e.png">

Please advise.

**Comment by timkpaine** [comment]
there are no intraday adjustments
