### ISSUE TITLE
splitsBasicDF not available

### ISSUE THREAD

**Issue by xescuder** [timkpaine/pyEX#351]
I need to get split basics from IEX. Reading the docs of pyEX, I've found the function splitsBasic and splitsBasicDF, but it seems is not available at 0.5 (latest).

Maybe is going to be included at 0.6 but I can't include this version (neither rc) using pipenv. Should I need to wait until the release or get the soure code and apply it by myself?

Thanks a lot.

**Comment by timkpaine** [comment]
I believe in `0.5.0`, basic splits is `stockSplits` and advanced splits is `splits`
https://github.com/timkpaine/pyEX/blob/v0.5.0/pyEX/stocks/fundamentals.py#L372

**Comment by xescuder** [comment]
Thanks @timkpaine, but IEX added a new call named stockBasicSplits, that needs less credits thant stockSplits. If not I am going to consume my credits quickly.

**Comment by timkpaine** [comment]
That is the same, `stockSplits` hits https://iexcloud.io/docs/api/#splits-basic
