### ISSUE TITLE
Add filter to IEX Cloud API calls

### ISSUE THREAD

**Issue by someone1** [timkpaine/pyEX#58]
https://iexcloud.io/docs/api/#filter-results

Let's us optimize bandwidth/weighting of each call - not to mention lowered memory footprint when processing data.

**Comment by timkpaine** [comment]
Thanks for bringing this up! This should be super easy to implement if anyone wants to do a PR, it can be passed through along with token and version to the underlying query function. Otherwise I will add it to my personal queue.
