### ISSUE TITLE
chartDF throws PyException

### ISSUE THREAD

**Issue by LEO-E-100** [timkpaine/pyEX#64]
After running:

```
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import pyEX as p

ticker = 'AMD'
timeframe = '1y'

df = p.chartDF(ticker, timeframe)
```

I get 

```
PyEXception: ('Response 403 - ', 'Forbidden')
```

**Comment by timkpaine** [comment]
If you haven't done so you should onboard to IEX cloud. The legacy APIs are being decommissioned

**Comment by LEO-E-100** [comment]
Sorry, but this response doesn't make a lot of sense to me. Do you mean I should interface directly with IEX REST API?

**Comment by timkpaine** [comment]
https://iextrading.com/developer/
 https://iextrading.com/developer/#sunset-schedule

According to schedule, IEX has begun decommissioning the old routes. This means `pyEX.chartDF(...)` has stopped working.

instead you can do `c = pyEX.client.Client(<your token>); c.chartDF(...)`

Data is still free, you can sign up and grab a token at https://iexcloud.io

Then for `pyEX` you can instantiate a client directly with your token or put it in the `IEX_TOKEN` environment variable.

Docs are here:
https://pyex.readthedocs.io/en/latest/api/pyEX.html#pyEX.client.Client

Xref
https://github.com/timkpaine/pyEX/issues/65

**Comment by LEO-E-100** [comment]
Ah I see, thank you so much.
