### ISSUE TITLE
Sandbox not working

### ISSUE THREAD

**Issue by jzstoller** [timkpaine/pyEX#67]
Using this code (with an appropriate sandbox token)
```
version = 'sandbox'
c = p.Client(api_token=token, version=version) 
symbol = 'AAPL'
print(c.delayedQuote(symbol))
```
It throws this error:

> TypeError: _getJsonIEXCloudSandbox() takes from 1 to 3 positional arguments but 4 were given

it looks like an issue in pyEx.common:

```
def _getJson(url, token='', version='', filter=''):
    '''for backwards compat, accepting token and version but ignoring'''
    token = token or os.environ.get('IEX_TOKEN')
    if token:
        if version == 'sandbox':
            return _getJsonIEXCloudSandbox(url, token, version, filter)
        return _getJsonIEXCloud(url, token, version, filter)

def _getJsonIEXCloudSandbox(url, token='', version='beta'):
    '''for iex cloud'''
    url = _URL_PREFIX2_SANDBOX.format(version='beta') + url
    resp = requests.get(urlparse(url).geturl(), proxies=_PYEX_PROXIES, params={'token': token})
    if resp.status_code == 200:
        return resp.json()
    raise PyEXception('Response %d - ' % resp.status_code, resp.text)
```

**Comment by timkpaine** [comment]
Ah looks like I didn't do this when doing https://github.com/timkpaine/pyEX/issues/58

Will fix ASAP and do a release

**Comment by Andre-Bravo** [comment]
Has this been resolved as it was closed?
I'm still facing this same issue on v0.1.14

**Comment by larroy** [comment]
Facing this issue as well.

**Comment by mios-xyz** [comment]
If you're installing from pip, it's possible that it's not pulling the latest version. I went into the common.py file and manually edited the following:

**BEFORE**
`def _getJsonIEXCloudSandbox(url, token='', version='beta'):`

**AFTER**
`def _getJsonIEXCloudSandbox(url, token='', version='beta', filter=''):`

Following: [(https://github.com/timkpaine/pyEX/issues/67#issuecomment-506916033)]

**Comment by timkpaine** [comment]
This is already fixed on the latest released version since June 21:
<img width="360" alt="Screen Shot 2019-07-23 at 8 48 48 AM" src="https://user-images.githubusercontent.com/3105306/61713560-e0990d00-ad26-11e9-9146-c9e4707320d8.png">

**Comment by mios-xyz** [comment]
Yes -- I installed from pip yesterday evening and encountered the same error. So I think it just needed to resync? Either way, looks like new release is on pip now. Thanks for addressing!
