### ISSUE TITLE
Legacy IEX API

### ISSUE THREAD

**Issue by aolsux** [timkpaine/pyEX#73]
Hey there!
First, thank you for your awesome work! Based on your pyEX, I set up https://github.com/xelonic-de/iex-data. It is sort of a hard fork of your code, with all the IEX cloud functionality stripped away.

Rational: IEX seems to plan to continue support for bare market data on their "old" API which will remain free, doesn't need authentication etc.

I plan to extend the iex-data with some more functionality (first I need to figure out my own requirements..)

So if any user plans to only use the old API maybe you can direct them there :-)

Regards, Martin

**Comment by timkpaine** [comment]
My library also supports the original api.

**Comment by timkpaine** [comment]
If there is sufficient demand we can undo the one commit, but otherwise there won't be any changes as all new stuff is on cloud

**Comment by timkpaine** [comment]
Be aware though that most of the main APIs have been deprecated https://iextrading.com/developer/#sunset-schedule

**Comment by timkpaine** [comment]
Also take note that IEX cloud has a free tier, and token authentication is not a big burden

**Comment by aolsux** [comment]
>> My library also supports the original api.

I know, it is up to you if you want to support both. I guess you would have to undo deprecations and reintroduce the websocket support.

>> Also take note that IEX cloud has a free tier, and token authentication is not a big burden

As i remember, their free tier has message rate limits thou. The classic api should allow for more free throughput.

>> Be aware though that most of the main APIs have been deprecated 

Yes, I removed all the functionality that was migrated from old the IEX api to IEX cloud.

The whole idea behind the fork, was to have a minimalistic package only for the "classic API" which has now reduced functionality.

**Comment by timkpaine** [comment]
I wouldn't use the websocket api, it was never particularly stable. The old api also has rate limits.
