### ISSUE TITLE
chart() should work on timeframe='5d'

### ISSUE THREAD

**Issue by martin-niklasson** [timkpaine/pyEX#76]
How to reproduce:

In [1]: import pyEX                                                                                                                                                                                                
In [2]: client = pyEX.client.Client()                                                                                                                                                                              
In [3]: client.chart(symbol='MSFT', timeframe='5d') 
[...]
PyEXception: Range must be in ['5y', '2y', '1y', 'ytd', '6m', '3m', '1m', '1d']

The TIMEFRAME_CHART in common.py line 31 should have '5d' instead of '1d'. ('1d' doesn't work either and throws a KeyError)

**Comment by timkpaine** [comment]
1d is supposed to do minute bars I think

**Comment by martin-niklasson** [comment]
This endpoint is messy, but 1d is not part of the possible ranges:
https://iexcloud.io/docs/api/#historical-prices

**Comment by timkpaine** [comment]
This method is a hold over from the v1 api, I will look to see how the functionality changed.

**Comment by timkpaine** [comment]
The behavior will now match the old api, in https://github.com/timkpaine/pyEX/pull/114

![Screen Shot 2020-08-04 at 15 21 11](https://user-images.githubusercontent.com/3105306/89335621-44f2ea00-d666-11ea-9677-a8a3204070c7.png)
