### ISSUE TITLE
Query for Bid and Ask data return empty DataFrame

### ISSUE THREAD

**Issue by shilewenuw** [timkpaine/pyEX#81]
Code: (my token string is stored in key)
```
import pyEX

df = pyEX.marketdata.http.topsDF(symbols = 'AAPL', token=key, version='stable')
print(df)
```
result:
Empty DataFrame
Columns: []
Index: []

**Comment by timkpaine** [comment]
@shilewenuw given there is no error, this seems to be the expected behavior. What behavior do you expect? Did you run this during market hours?
