### ISSUE TITLE
[feature request] pls add more method: upcoming-events

### ISSUE THREAD

**Issue by mingwugmail** [timkpaine/pyEX#85]
pls add more method

https://iexcloud.io/docs/api/#upcoming-events

Available Methods
- [ ] GET /stock/{symbol}/upcoming-events
- [ ] GET /stock/{symbol}/upcoming-dividends
- [ ] GET /stock/{symbol}/upcoming-splits
- [ ] GET /stock/{symbol}/upcoming-earnings
- [x] GET /stock/{symbol}/upcoming-ipos

Examples
/stock/market/upcoming-events
/stock/market/upcoming-earnings
/stock/market/upcoming-dividends
/stock/market/upcoming-splits
/stock/market/upcoming-ipos
/stock/aapl/upcoming-events
/stock/aapl/upcoming-earnings
/stock/aapl/upcoming-dividends
/stock/aapl/upcoming-splits
/stock/aapl/upcoming-ipos

**Comment by timkpaine** [comment]
upcoming IPOs is implemented:
https://github.com/timkpaine/pyEX/blob/b9d3da4b46e4c73ccc24a7cc745e755e6ed96212/pyEX/stocks.py#L1245
