### ISSUE TITLE
pyEX.common.PyEXception: Old IEX API is deprecated. For a free API token, sign up at https://iexcloud.io

### ISSUE THREAD

**Issue by TechniumUnlimited** [timkpaine/pyEX#93]
pyEX.common.PyEXception: Old IEX API is deprecated. For a free API token, sign up at https://iexcloud.io

Is API deprecated or am I doing something wrong?

**Comment by timkpaine** [comment]
the former, sign up for a [free account on IEX cloud](https://iexcloud.io/s/6332a3c3)

**Comment by TechniumUnlimited** [comment]
Hi I already have an account there

**Comment by timkpaine** [comment]
@TechniumUnlimited you should be able to use the [client api](https://github.com/timkpaine/pyEX/blob/master/examples/client.ipynb) then. Try instantiating a `Client` and then calling the method with the same name as the function you were calling.
